.devcontainer/devcontainer.json, .github/workflows/app-pull-request.yml, .github/workflows/backstage-catalog-helper.yml, .github/workflows/export_github_data.yml, .github/workflows/s3-backup.yml, .github/workflows/shellcheck.yml, .github/workflows/tf-apply-prod.yml, .github/workflows/tf-apply-staging.yml, .github/workflows/tf-plan-prod.yml, .github/workflows/tf-plan-staging.yml, .github/workflows/workflow-failure.yml, .gitignore, README.md, terragrunt/aws/cloudfront.tf, terragrunt/aws/ecr.tf, terragrunt/aws/lambda.tf, terragrunt/aws/locals.tf, terragrunt/aws/oidc.tf, terragrunt/aws/route53.tf, terragrunt/aws/variables.tf, terragrunt/env/common/common_variables.tf, terragrunt/env/common/provider.tf, terragrunt/env/prod/.terraform.lock.hcl, terragrunt/env/prod/env_vars.hcl, terragrunt/env/prod/terragrunt.hcl, terragrunt/env/root.hcl, terragrunt/env/staging/.terraform.lock.hcl, terragrunt/env/staging/env_vars.hcl, terragrunt/env/staging/terragrunt.hcl
Add the Terraform and GitHub workflows required to manage the doc site's Lambda function and CloudFront distribution.
=> feat: add Terraform and plan/apply workflows

terragrunt/aws/cloudfront.tf, terragrunt/aws/ecr.tf, terragrunt/aws/waf.tf
Add a WAF to protect the Docs site CloudFront distribution.
Add an ECR policy to remove old images that are no longer needed.
=> feat: add a WAF ACL for the CloudFront distribution

app/public/styles.css
Adding a small adjustment to the default margins of the heading and text elements to ensure consistency with the default values used by the corresponding GCDS components.
- Heading `margin-block-start` was changed from `var(--gcds-spacing-300)` to `var(--gcds-spacing-600)`.
- List and paragraph `margin-block-start` was changed from `var(--gcds-spacing-300)` to `var(--gcds-spacing-0)`.
=> style: modify default margin for heading and text elements

.github/workflows/docker-deploy-staging.yml, .github/workflows/docker-vulnerability-scan.yml
Add the missing `sha-` prefix to the Staging Docker image tag.
Also fixes the path to the Dockerfile in the vulnerability scan action.
=> fix: docker deploy staging workflow

terragrunt/aws/alarms.tf, terragrunt/aws/locals.tf
Add alarms to monitor the docs site.  These rely on the SNS topics created by the CDS Superset Terraform.
=> feat: add error and health check alarms

terragrunt/aws/alarms.tf
Fix the syntax for the CloudWatch metric filter pattern.
Fix a typo in the Lambda invocation alarm name.
=> fix: CloudWatch error metric filter pattern

terragrunt/aws/lambda.tf
Reduce the function memory based.  The function invocation report shows that the average memory being used by invocations is 171MB.
The following query was used to determine memory use:
```
filter @type = "REPORT"
| stats max(@memorySize / 1000 / 1000) as provisonedMemoryMB,
min(@maxMemoryUsed / 1000 / 1000) as smallestMemoryRequestMB,
avg(@maxMemoryUsed / 1000 / 1000) as avgMemoryUsedMB,
max(@maxMemoryUsed / 1000 / 1000) as maxMemoryUsedMB,
provisonedMemoryMB - maxMemoryUsedMB as overProvisionedMB
```
provisonedMemoryMB | smallestMemoryRequestMB | avgMemoryUsedMB | maxMemoryUsedMB | overProvisionedMB
-- | -- | -- | -- | --
1 | 4096 | 81 | 171.5032 | 227 | 3869
- [Example Lambda queries](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_QuerySyntax-examples.html#CWL_QuerySyntax- …
=> fix: reduce function memory

terragrunt/aws/alarms.tf, terragrunt/aws/lambda.tf, terragrunt/aws/route53.tf
Replace the Route53 health check with an EventBridge rule that invokes the function every 5 minutes.  This will keep a warm instance of the function available to handle requests.
- https://github.com/cds-snc/platform-core-services/issues/681
=> feat: add an EventBridge rule to warm the function

terragrunt/aws/lambda.tf
Update the function's environment variables to the names expected by the Go WordPress proxy.
=> fix: lambda function's environment vars

.github/workflows/app-pull-request.yml, app/Makefile, app/cmd/server/main.go, app/internal/handlers/robots.go, app/internal/handlers/robots_test.go
Add a `robots.txt` that blocks all search indexing.
Also updates the PR workflow to use Makefile targets.
- https://github.com/cds-snc/platform-core-services/issues/682
=> feat: add robots.txt file

app/internal/api/wordpress.go, app/internal/handlers/page.go, app/internal/handlers/page_test.go
Update the Page handler so that a 404 is returned when a WordPress page is not found.
Update the checks for invalid characters in the URL to only allow alphanumeric, slashes, dashed and underscores.
=> fix: properly return a 404 when page not found

.github/workflows/tf-apply-prod.yml, .github/workflows/tf-apply-staging.yml, .github/workflows/tf-plan-prod.yml, .github/workflows/tf-plan-staging.yml, terragrunt/aws/variables.tf, terragrunt/aws/waf.tf
The status checker's IP address is occasionally being identified as in the US so we're adding a secret Upptime request header that will allow those requests to succeed.
=> fix: update CA geo restriction with Upptime header 

app/static/css/styles.css, app/templates/layout.html
Upgrade to the latest release and remove custom CSS styles that are no longer needed.
=> chore: upgrade to v1.6.0 release of the GCDS utility library

.github/workflows/workflow-failure.yml
Update the workflow failure to post notifications to the correct ops channel depending on which environment workflow has failed.
=> fix: post workflow failure messages to correct env channel

app/.env.example, app/cmd/server/main.go, app/internal/config/config.go, app/internal/handlers/page.go, app/internal/handlers/page_test.go, app/pkg/models/wordpress.go, app/pkg/models/wordpress_test.go, app/templates/layout.html, terragrunt/aws/lambda.tf, terragrunt/aws/variables.tf, terragrunt/env/prod/terragrunt.hcl, terragrunt/env/staging/terragrunt.hcl
Update the site so that if a Google Analytics ID is provided, the tracking JavaScript is also loaded on the page.
This will allow us to selectively deploy different tracking IDs to different environments, or omit environments from tracking.
- https://github.com/cds-snc/platform-core-services/issues/744
=> feat: add Google Analytics to prod

.github/workflows/docker-deploy-staging.yml
Update the Docker deploy workflow so they use the commit SHA of the `main` branch commit that triggered its invocation.
=> fix: race condition to retrieve commit SHA

.github/workflows/cache-invalidate-staging.yml, .github/workflows/lambda-restart-prod.yml, .github/workflows/lambda-restart-staging.yml
Add workflows that can be used to force a restart of the site's Lambda function.  This can be used when there are WordPress menu changes made that should be reflected on the site.
Additionally, once the Lambda restart workflow is finished it will also trigger a cache invalidation.
=> feat: add Lambda restart workflows

.github/workflows/lambda-restart-prod.yml, .github/workflows/lambda-restart-staging.yml
Update the restart Lambda workflow to use the correct AWL CLI command needed to update a function's description.
=> fix: update to use correct AWS CLI command

.github/workflows/dependency-security-update.yml
Add a workflow that posts to Slack when a new dependency security PR is opened by Renovate.
- https://github.com/cds-snc/platform-core-services/issues/764
=> feat: add Slack notification for Security PRs

.github/workflows/app-pull-request.yml, .github/workflows/backstage-catalog-helper.yml, .github/workflows/cache-invalidate-prod.yml, .github/workflows/cache-invalidate-staging.yml, .github/workflows/docker-apply-prod.yml, .github/workflows/docker-apply-staging.yml, .github/workflows/docker-deploy-prod.yml, .github/workflows/docker-deploy-staging.yml, .github/workflows/export_github_data.yml, .github/workflows/labels.yml, .github/workflows/lambda-restart-prod.yml, .github/workflows/lambda-restart-staging.yml, .github/workflows/ossf-scorecard.yml, .github/workflows/tf-apply-prod.yml, .github/workflows/tf-apply-staging.yml, .github/workflows/tf-plan-prod.yml, .github/workflows/tf-plan-staging.yml
Update the GitHub action version pinning so that immutable commit SHAs are used.  This will make it more difficult for malicious code to be injected into our workflows.
- https://github.com/cds-snc/platform-core-services/issues/758
=> fix: pin GitHub actions to commit SHAs
